version: "3"

services:
  api:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - API_NAME=$API_NAME
      - API_URL=$API_URL
      - MONGODB_PROTOCOL=$MONGODB_PROTOCOL
      - MONGODB_USER=$MONGODB_USER
      - MONGODB_PASSWORD=$MONGODB_PASSWORD
      - MONGODB_SERVER=$MONGODB_SERVER
      - MONGODB_PORT=$MONGODB_PORT
      - MONGODB_DATABASE=$MONGODB_DATABASE
    ports:
      - $PORT:$PORT
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:27017
    restart: always
    volumes:
      - mongodb_volume:/data/db

volumes:
  mongodb_volume:
