version: "3"

services:
  api:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=$PORT
      - API_NAME=$API_NAME
    ports:
      - $PORT:$PORT
    restart: always

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    restart: always
